name: konsumer_core
description: "A Riverpod consumer for easier provider consumption"
version: 0.0.4

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0